Initial notebook to generate omega scans from background files
ML4GW/aframev2 pull request #108
Opened 2024-03-07 04:23 UTC by ricco-hub

Made notebook that generates omega scans for the top _n_ highest detection statistics from the `background.h5` files for both Livingston and Hanford. Saves plots as `png` files.

2024-03-11 14:58 UTC, wbenoit26 commented
This looks nice! Can you convert it to a python file so I can leave comments on the relevant lines? Just remove the `%matplotlib inline`, add a function:
```
def main(n: int, background_file: str, background_dir: str):
    times, shifts = find_max_times(background_file, n)
    load_background(background_dir, times=times, shifts=shifts)
```

and put the following at the bottom of the script:
```
if __name__ == "__main__":
    background_file = '/home/ricco.venterea/results/my-first-run/infer/background.h5'
    background_dir = '/home/ricco.venterea/data/test/background'
    n = 2
    main(background_file, background_dir, n)
```

And everything should work the same as before.

2024-03-18 20:56 UTC, wbenoit26 requested changes

2024-03-18 20:56 UTC, wbenoit26 commented on projects/plots/plots/omega_scan.py
> +if __name__ == "__main__":
We'll want to set this up so we can run it as part of the `luigi` structure that Ethan has set up, but I'll add comments about that on a future pass through. For now, let's address these comments and make sure everything works.

2024-03-20 18:33 UTC, EthanMarx commented
This is awesome, will be nice to have this automated.

2024-03-20 18:35 UTC, EthanMarx commented on projects/plots/plots/omega_scan.py
> +    background = h5py.File(path,'r')
This obviously works, but would make some things cleaner if you used the `EventSet` object directly from the ledger. i.e.

`background = EventSet.read(path)`

2024-03-22 23:05 UTC, ricco-hub commented on projects/plots/plots/omega_scan.py
> +            if int(start_time) <= t <= int(end_time):
I don't recall having an issue but just wanted to make sure this inequality remained true; I'll remove it.

2024-07-22 19:46 UTC, closed without merging